name: Coverage Check

on: [push, pull_request]

permissions:
  contents: read

jobs:
  coverage:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Set up Python 3.14
      uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
      with:
        python-version: '3.14'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install test tools
      run: |
        pip install hypothesis
        pip install pytest
        pip install pytest-cov

    - name: Install package
      run: pip install -e .

    - name: Run tests with coverage check (100% enforced)
      run: pytest --cov=userprovided --cov-fail-under=100 tests/
